// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ben.monlabel.domain;

privileged aspect Invite_Roo_JavaBean {
    
    public java.lang.String Invite.getAdresseMail() {
        return this.adresseMail;
    }
    
    public void Invite.setAdresseMail(java.lang.String adresseMail) {
        this.adresseMail = adresseMail;
    }
    
}
